name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build-x86:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake
        run: sudo apt-get -y install cmake 

      - name: Build
        run: cmake . && make

      - name: Print "Hello World"
        run: ./HelloWorld

  build-arm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install QEMU
        run: |
          sudo apt update &&
          sudo apt install -y libc6-armhf-cross &&
          sudo apt install -y qemu-user &&
          export QEMU_LD_PREFIX=/usr/arm-linux-gnueabi

      - name: Install ARM GCC cross-compiler
        run: sudo apt install -y gcc-arm-linux-gnueabihf 

      - name: Install CMake
        run: sudo apt install -y cmake

      - name: Build
        run: cmake -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc . && make

      - name: Print "Hello World"
        run: sudo qemu-arm ./HelloWorld
