name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build-x86:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake
        run: sudo apt-get -y install cmake 

      - name: Build
        run: cmake . && make

      - name: Print "Hello World"
        run: ./HelloWorld

  build-arm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup QEMU
        run: |
         wget https://github.com/multiarch/qemu-user-static/releases/download/v6.0.0-2/qemu-arm-static &&
         chmod +x qemu-arm-static
         sudo mv qemu-arm-static /usr/local/bin
         qemu-arm-static --version
        
      - name: Install ARM GCC cross-compiler
        run: sudo apt install -y gcc-arm-linux-gnueabihf 

      - name: Install CMake
        run: sudo apt install -y cmake

      - name: Build
        run: cmake -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc . && make

      - name: Print "Hello World"
        run: qemu-arm-static ./HelloWorld
